### ISSUE TITLE
インデントがずれているので直しておきましょう

### ISSUE THREAD

**Issue by totsumaru** [morimotoyuuki111/blog#12]
https://github.com/morimotoyuuki111/blog/blob/8a77c33660c60e0199b8ac855b4218a7fe851d15/dev/go-tech-blog/model/article.go#L11-L15

**Comment by morimotoyuuki111** [comment]
https://github.com/morimotoyuuki111/blog/blob/main/dev/go-tech-blog/model/article.go

修正いたしました。
確認お願いいたします。

**Comment by totsumaru** [comment]
あれ、直ってないような気がしますがどうでしょう？

**Comment by morimotoyuuki111** [comment]
すいません。もう一度確認します

**Comment by morimotoyuuki111** [comment]
https://github.com/morimotoyuuki111/blog/blob/main/dev/go-tech-blog/model/article.go

どうでしょうか？

**Comment by totsumaru** [comment]
<img width="546" alt="スクリーンショット 2022-08-05 15 06 22" src="https://user-images.githubusercontent.com/98322774/183012361-3d023109-e9ad-47cf-b546-494180249da8.png">

僕の方ではズレて見えますが、森本さんの方では正しく見えてるんですよね。。。  
自分のPCがおかしいのかもしれないですね。。

**Comment by totsumaru** [comment]
もしスペースで揃えているなら、Tabでインデントを揃えるようにするといいと思います。
https://qiita.com/ichiichi_1115/items/91c018106b68cb6101c4

**Comment by totsumaru** [comment]
vscode使ってるならこんなのも
https://konsuki.com/5411/

**Comment by morimotoyuuki111** [comment]
スクショにはなってしましますがこのような形ですね

<img width="1440" alt="スクリーンショット 2022-08-05 15 14 13" src="https://user-images.githubusercontent.com/102967614/183013402-3c50a85c-34cb-4e82-a99a-78e36e472fe1.png">

**Comment by totsumaru** [comment]
<img width="174" alt="スクリーンショット 2022-08-05 15 16 49" src="https://user-images.githubusercontent.com/98322774/183013651-801a4c67-a39a-4514-ac56-a3070ee1e846.png">

ここの開始位置がバラバラになってるので、先頭の位置を揃えておきましょう。
これを「インデント」と言います。

汚いコードは間違いなくマイナス評価になるので、文頭（インデント）は必ず揃えるようにしましょう。

**Comment by totsumaru** [comment]
先ほど送ったvscodeのショートカットを使って、必ずフォーマットをかけることをお勧めします。

**Comment by morimotoyuuki111** [comment]
どうでしょうか？
<img width="1440" alt="スクリーンショット 2022-08-05 15 14 13" src="https://user-images.githubusercontent.com/102967614/183015964-8cbc8c8f-bb5d-4463-b876-046eb7439ca9.png">

**Comment by totsumaru** [comment]
```go
import (
  "database/sql"
  "time"
  
  "go-tech-blog/model"
)
```
のように先頭の位置が揃わないでしょうか？

**Comment by morimotoyuuki111** [comment]
[article.go]も試してみました(https://github.com/morimotoyuuki111/blog/blob/8a77c33660c60e0199b8ac855b4218a7fe851d15/dev/go-tech-blog/model/article.go#L11-L15)
<img width="1440" alt="スクリーンショット 2022-08-05 15 14 13" src="https://user-images.githubusercontent.com/102967614/183016276-e028671b-5bd1-4941-b58e-3f4369656b7e.png">

**Comment by morimotoyuuki111** [comment]
それは揃います！
<img width="1440" alt="スクリーンショット 2022-08-05 15 36 20" src="https://user-images.githubusercontent.com/102967614/183016581-6e503a1e-ffc2-440e-ad5d-3fc4f6b23d76.png">
！

**Comment by totsumaru** [comment]
揃った状態で、ドキュメントに記載しておきましょう。

**Comment by morimotoyuuki111** [comment]
只今、再度アップロードしました。
acticle.goのインデントも揃った状態で記載しました。
