### ISSUE TITLE
インデントがずれているので直しておきましょう

### ISSUE THREAD

**Issue by totsumaru** [morimotoyuuki111/blog#13]
https://github.com/morimotoyuuki111/blog/blob/8a77c33660c60e0199b8ac855b4218a7fe851d15/dev/go-tech-blog/repository/article_repository.go#L4-L7

**Comment by morimotoyuuki111** [comment]
https://github.com/morimotoyuuki111/blog/blob/main/dev/go-tech-blog/repository/article_repository.go

修正いたしました。
確認お願いいたします。

**Comment by totsumaru** [comment]
こちらも直ってないような気がしますが、、、？

**Comment by morimotoyuuki111** [comment]
すいません、こちらも確認します

**Comment by morimotoyuuki111** [comment]
https://github.com/morimotoyuuki111/blog/blob/main/dev/go-tech-blog/repository/article_repository.go

こちらもおそらく大丈夫だと思います。

**Comment by totsumaru** [comment]
```go
type Article struct {
	ID      int       `db:"id" form:"id"`
	Title   string    `db:"title" form:"title" validate:"required,max=50"`
	Body    string    `db:"body" form:"body" validate:"required"`
	Created time.Time `db:"created"`
	Updated time.Time `db:"updated"`
}
```
こちらもこんな感じで揃えたいですね！

**Comment by morimotoyuuki111** [comment]
ありがとうございます。
こちらも揃えて保存しました。
https://github.com/morimotoyuuki111/blog/blob/main/dev/go-tech-blog/model/article.go

**Comment by totsumaru** [comment]
OKです！今後も意識して記載しましょう！

**Comment by morimotoyuuki111** [comment]
ありがとうございます。
