### ISSUE TITLE
goose のインストールのインストールについて

### ISSUE THREAD

**Issue by morimotoyuuki111** [morimotoyuuki111/blog#2]
なぜgo-tech-blogフォルダ内で、

```go
go install github.com/pressly/goose/v3/cmd/goose@latest
```
インストールできたのでしょうか？

**Comment by totsumaru** [comment]
go get または go install すると、GOPATHで設定したフォルダにコマンドが自動でインストールされます。
（ただし、インストール元でコマンドの設定があるもののみ）

https://go.kimama-it.blog/golang%E3%82%92%E5%88%A9%E7%94%A8%E3%81%97%E3%81%A6%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9%E3%81%AE%E3%83%9E%E3%82%A4%E3%82%B0%E3%83%AC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E7%AE%A1/
この記事を読んでみるといいかもしれません。
