### ISSUE TITLE
マイグレーションについて

### ISSUE THREAD

**Issue by morimotoyuuki111** [morimotoyuuki111/blog#5]
バージョンの違いにもよりますがマイグレーションファイルはどのように作られるのでしょうか？一つずつ教えていただきたいです。

**Comment by totsumaru** [comment]
私自身、マイグレーションファイルは使用せず、gooseも使わないので細かい挙動がわからず、すみません。。

MySQLを直接触らなくてもマイグレーションファイルを更新すれば楽に変更できるよ！というものですが、個人的には直接SQLを書き換えた方がシンプルなので、直接書き換えています。
（そんなに書き換えることはないので）

**Comment by morimotoyuuki111** [comment]
SQL文を直接書き換えるというのはMySQLに直接書いていくという意味でしょうか？

**Comment by totsumaru** [comment]
そうですね！
lesson 1-9でやったようにMySQLを起動してSQLのコマンドで操作します。

**Comment by morimotoyuuki111** [comment]
そうなんですね。
データベースの設計がしっかりできてないと直接書くことは難しそうですが慣れれば直接のが安心ではありますね。
ginでマイグレーションが作れなかったら直接
