### ISSUE TITLE
go get -u -v github.com/pilu/freshについて

### ISSUE THREAD

**Issue by morimotoyuuki111** [morimotoyuuki111/blog#6]
結論　freshの動作確認をしたらcommand not foundのエラーが出ました。

流れ
```go
go get -u -v github.com/pilu/fresh
```
を試した後
```go
which fresh
```
を試したらパスの確認はできませんでした。

そのため先日教わったgooseのエラー時みたくgo get -u -v github.com/pilu/freshのインストールではなくパスを通すコマンドのインストールが必要なのでしょうか？

**Comment by totsumaru** [comment]
github.com/pilu/fresh

これが、インストール元のgithubです。
最終更新が6年前なので、おそらくバージョンが古くて対応してない可能性があります。

ホットリロードは、完全にオプションのため今回は無しで行きましょう。
ホットリロードとは、goを再起動することなく変更を反映してくれるものですが、私はあまり使ってないので、使わなくても問題ありません！

**Comment by morimotoyuuki111** [comment]
わかりました。思ったのが検索していてバージョンが古いものが多い記事が多くて苦戦することも今後出てくると思うんですけどその場合はドキュメントで最新バージョンを探す認識でよろしいのでしょうか？

**Comment by totsumaru** [comment]
そうですね！基本的にはインストール元のgithubを見てみるといいと思います。

最終更新が数年前の場合は、Goの最新バージョンに対応していない可能性が高いので注意が必要です。
